[main]
font=FiraMono Nerd Font:size=16
# Doesnt work setting it to alacritty here...
terminal=wezterm
prompt="> "
icon-theme=Adwaita
icons-enabled=yes
lines=13
fields=name,generic,comment,categories,filename,keywords
width=50
horizontal-pad=20
vertical-pad=10
inner-pad=10
show-actions=no

[colors]
background=282c34dd
text=abb2bfff
match=61afefff
selection=3e4451ff
selection-text=abb2bfff
border=61afefff

[border]
width=2
radius=20
